export async function fetchExperiences() {
  await new Promise((resolve) => setTimeout(resolve, 3000));

  return [
    {
      id: '1',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/seven.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '2',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/eight.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '3',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/one.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '4',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/two.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '5',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/three.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '6',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/five.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
    {
      id: '7',
      name: 'Mt Kenya (Point Thompson)',
      image: '/images/four.jpg',
      rating: '4.5',
      reviews: 54,
      location: 'Central Kenya',
      distance: '22 KM',
      duration: '2 Hrs 30 mins',
    },
  ];
}
