import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from '@/app/ui/fonts';
import Image from "next/image";
import Nav from "@/app/ui/nav";
import AuthActions from "@/app/ui/authActions";
import Link from "next/link";
import GlobalLoading from "@/app/ui/globalLoading";
import DownloadApp from "@/app/ui/downloadApp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <GlobalLoading />
        <div className="grid grid-cols-12 md:gap-4 bg-white">
          <DownloadApp />
          <div className="col-span-12 mx-4 md:mx-0 md:col-start-2 md:col-span-10">
            <div className="inline-flex justify-between w-full md:grid md:grid-cols-2 md:gap-4 md:mt-10">
              <div className="flex items-center md:items-start h-[40px]">
                <Link href="/" className="hidden md:block">
                  <Image src="/images/logo.svg" alt="Oltukai logo" width={100} height={80} className="mr-6" />
                </Link>
                <Nav />
              </div>
              <div className="flex items-center md:items-start justify-end h-[40px]">
                <AuthActions />
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
