import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { satoshi } from '@/app/ui/fonts';
import Image from 'next/image';
import Nav from '@/app/ui/nav';
import AuthActions from '@/app/ui/authActions';
import Link from 'next/link';
import GlobalLoading from '@/app/ui/globalLoading';
import DownloadApp from '@/app/ui/downloadApp';
import NotificationProvider from '@/providers/NotificationProvider';
import SessionProvider from '@/providers/SessionProvider';
import { ReduxProvider } from './redux-provider';
import IconRadioButtonGroup from '@/app/ui/iconRadioButtonGroup';
import { FilterHorizontalIcon, hugeiconsLicense, Search01Icon } from '@hugeicons/react-pro';

hugeiconsLicense(
  '890e3333f427f30eb0b744e4d32392a6RT00NzkxODg2MzcwMDAwLFM9cHJvLFY9MSxQPUd1bXJvYWQsU1Q9QjVBMzQ1NzMsRVQ9MDIxMUY0RkM=',
);
export const metadata: Metadata = {
  title: 'Tukai',
  description: 'Generated by create next app',
};

const Search = () => {
  return (
    <div className="inline-flex h-10 w-full items-center justify-between rounded-full border-[1px] border-gray-200 bg-white py-4 pl-4 pr-1">
      <Search01Icon size={20} className="mr-2 text-gray-500" variant="twotone" />
      <div className="flex w-full flex-col md:w-[90%]">
        <p className="mb-0 text-xs text-gray-700">What&apos;s the plan?</p>
        <input
          className="mt-[2px] h-full w-full text-[11px] outline-0 placeholder:text-[11px] placeholder:text-gray-400 hover:border-primary focus:border-primary"
          placeholder={`Any experience . Anywhere . Any day`}
        />
      </div>
      <div className="ml-2 flex h-[30px] w-[36px] items-center justify-center rounded-full bg-gray-100">
        <FilterHorizontalIcon className="text-gray-800" size={15} variant="twotone" />
      </div>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <ReduxProvider>
          <SessionProvider>
            <NotificationProvider>
              <GlobalLoading />
              <div className="grid grid-cols-12 border-b-[1px] border-gray-100 bg-white md:gap-4">
                <DownloadApp />
                <div className="col-span-12 mx-4 md:col-span-10 md:col-start-2 md:mx-0">
                  <div className="inline-flex h-[80px] w-full items-center justify-between md:mt-6">
                    <div className="flex h-full items-center">
                      <Link href="/" className="hidden h-full items-center md:flex">
                        <Image
                          src="/images/logo.svg"
                          alt="Oltukai logo"
                          width={80}
                          height={70}
                          className="mr-6"
                        />
                      </Link>
                      <Nav />
                    </div>
                    <div className="inline-flex">
                      <div className="mr-2 hidden w-72 md:block">
                        <Search />
                      </div>
                      <IconRadioButtonGroup />
                    </div>
                    <div className="flex h-full items-center justify-end">
                      <AuthActions />
                    </div>
                  </div>
                </div>
              </div>
              {children}
            </NotificationProvider>
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
